#pragma once

enum {
    FRAME_METHOD,
    FRAME_HEADER,
    FRAME_BODY,
    FRAME_HEARTBEAT   = 8,
    REPLY_SUCCESS     = 200,
    FRAME_END         = 206,
    CONTENT_TOO_LARGE = 311,
    NO_CONSUMERS      = 313,
    CONNECTION_FORCED = 320,
    INVALID_PATH      = 402,
    ACCESS_REFUSED,
    NOT_FOUND,
    RESOURCE_LOCKED,
    PRECONDITION_FAILED,
    FRAME_ERROR       = 501,
    SYNTAX_ERROR,
    COMMAND_INVALID,
    CHANNEL_ERROR,
    UNEXPECTED_FRAME,
    RESOURCE_ERROR,
    NOT_ALLOWED       = 530,
    NOT_IMPLEMENTED   = 540,
    INTERNAL_ERROR,
    FRAME_MIN_SIZE    = 4096
};
